"""Bounded P4/P5 execution gateway primitives."""

from .shadow_ledger import (
    FORWARD_OBSERVATION_SCHEMA,
    POLICY_GATE_RECEIPT_SCHEMA,
    ShadowLedgerError,
    build_shadow_ledger_receipt,
    build_tqqq_shadow_cycle_input,
    calculate_forward_observation_sha256,
    calculate_policy_gate_receipt_sha256,
    validate_shadow_cycle_input,
    validate_shadow_ledger_receipt,
)
from .shadow_receipt_store import (
    ADMISSION_SCHEMA,
    PERSISTENCE_RESULT_SCHEMA,
    CreateOnlyShadowReceiptStore,
    InMemoryShadowReceiptStore,
    ShadowReceiptStoreError,
    build_shadow_receipt_admission,
    calculate_shadow_receipt_admission_sha256,
    persist_shadow_cycle_outcome,
    validate_shadow_receipt_admission,
    validate_shadow_receipt_persistence_result,
)
from .shadow_risk_gate_decision import (
    DETERMINISTIC_RISK_GATE_DECISION_SCHEMA,
    P5_RISK_GATE_DECISION_ENVELOPE_SCHEMA,
    P5_RISK_GATE_DECISION_REFERENCE_SCHEMA,
    ShadowRiskGateDecisionError,
    ShadowRiskGateDecisionMismatchError,
    ShadowRiskGateDecisionProhibitedError,
    build_p5_risk_gate_decision_reference,
    calculate_p5_risk_gate_decision_envelope_sha256,
    validate_p5_risk_gate_decision_reference,
)
from .shadow_scheduler import (
    SCHEDULER_RESULT_SCHEMA,
    ShadowCycleOutcome,
    ShadowSchedulerError,
    run_tqqq_shadow_cycle,
    validate_shadow_scheduler_result,
)

__all__ = [
    "ADMISSION_SCHEMA",
    "DETERMINISTIC_RISK_GATE_DECISION_SCHEMA",
    "FORWARD_OBSERVATION_SCHEMA",
    "P5_RISK_GATE_DECISION_ENVELOPE_SCHEMA",
    "P5_RISK_GATE_DECISION_REFERENCE_SCHEMA",
    "PERSISTENCE_RESULT_SCHEMA",
    "POLICY_GATE_RECEIPT_SCHEMA",
    "SCHEDULER_RESULT_SCHEMA",
    "CreateOnlyShadowReceiptStore",
    "InMemoryShadowReceiptStore",
    "ShadowCycleOutcome",
    "ShadowLedgerError",
    "ShadowReceiptStoreError",
    "ShadowRiskGateDecisionError",
    "ShadowRiskGateDecisionMismatchError",
    "ShadowRiskGateDecisionProhibitedError",
    "ShadowSchedulerError",
    "build_p5_risk_gate_decision_reference",
    "build_shadow_ledger_receipt",
    "build_shadow_receipt_admission",
    "build_tqqq_shadow_cycle_input",
    "calculate_forward_observation_sha256",
    "calculate_p5_risk_gate_decision_envelope_sha256",
    "calculate_policy_gate_receipt_sha256",
    "calculate_shadow_receipt_admission_sha256",
    "persist_shadow_cycle_outcome",
    "run_tqqq_shadow_cycle",
    "validate_p5_risk_gate_decision_reference",
    "validate_shadow_cycle_input",
    "validate_shadow_ledger_receipt",
    "validate_shadow_receipt_admission",
    "validate_shadow_receipt_persistence_result",
    "validate_shadow_scheduler_result",
]
